<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WH5000703" name="com.test.LoginTest" tests="1" failures="0" timestamp="30 Nov 2015 16:51:38 GMT" time="0.666" errors="1">
  <testcase name="loginWithGuestAccount" time="0.666" classname="com.test.LoginTest">
    <error type="java.lang.RuntimeException" message="cucumber.runtime.PendingException: TODO: implement me">
      <![CDATA[java.lang.RuntimeException: cucumber.runtime.PendingException: TODO: implement me
	at com.legalmonkeys.test.AbstractCucumberTest.run(AbstractCucumberTest.java:76)
	at com.legalmonkeys.test.AbstractCucumberTest.run(AbstractCucumberTest.java:27)
	at com.test.LoginTest.loginWithGuestAccount(LoginTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: cucumber.runtime.PendingException: TODO: implement me
	at com.test.LoginTest.Prepared_user_with_username_and_password_(LoginTest.java:25)
	at âœ½.Given Prepared user with username <"SuccessfulUsername"> and password <"12345">(src\test\resources\com\test\login.feature:4)
]]>
    </error>
  </testcase> <!-- loginWithGuestAccount -->
</testsuite> <!-- com.test.LoginTest -->
